<template>
  <div>
    <Header></Header>
  </div>
  <div class="container mt-5 pt-4">
    <div class="row">
      <div class="col-sm-12 col-md-3">
        <Sidebar></Sidebar>
      </div>
      <div class="col-sm-12 col-md-9">
        <router-view></router-view>
      </div>
    </div>
  </div>
</template>
<script>
import Header from '@/components/Header.vue'
import Sidebar from '@/components/Sidebar.vue'
export default {
  name: 'Home',
  components: {
    Header,
    Sidebar
  }
}
</script>
<style>
  .principal-container{
    -webkit-align-items: center;
    align-items: center;
    -webkit-flex-direction: column;
    flex-direction: column;
    overflow: visible;
    display: flex;
    width: 100%;
  }
  .secondary-container{
    width: 100%;
    margin-top: 0;
    display: flex;
  }
  .search-sidebar{
    -webkit-flex: 1 1;
    flex: 1 1;
    -webkit-flex-wrap: wrap;
    flex-wrap: wrap;
    max-width: 294px;
    min-width: 210px;
    padding-right: 14px;
    width: 100%;
  }
  .search-results {
    display: -webkit-flex;
    display: flex;
    -webkit-flex-direction: column;
    flex-direction: column;
    width: 885px;
  }
  .global-btn{
    background-color: #470076 !important;
    border: none !important;
    font-weight: 600 !important;
    font-size: 15px !important;
    height: 38px;
  }
  .global-btn:hover{
    background-color: #7300bf !important;
  }





  .loading-container{
    width: 100%;
    text-align: center;
    height: 100vh;
    padding-top: 100px;
  }
  /* LOADING STYLES */
  @keyframes ldio-0qu31ifis2pl {
    0%    { transform: translate(2px,2px) }
   33.33% { transform: translate(102px,2px) }
   66.66% { transform: translate(42px,102px) }
  100%    { transform: translate(2px,2px) }
}


.ldio-0qu31ifis2pl > div {
  transform: scale(0.8);
  transform-origin: 100px 100px;
}

.ldio-0qu31ifis2pl > div > div {
  animation: ldio-0qu31ifis2pl 1s linear infinite;
  position: absolute
}

.ldio-0qu31ifis2pl > div > div div:nth-child(1) {
  width: 72px;
  height: 72px;
  border-radius: 50%;
  border: 12px solid #470076;
  background: #46dff0
}

.ldio-0qu31ifis2pl > div > div div:nth-child(2) {
  width: 17px;
  height:  51px;
  transform: rotate(-45deg);
  background: #470076;
  border-radius: 0 0 8px 8px;
  position: absolute;
  top: 68px;
  left: 85px
}
.loadingio-spinner-magnify-mn2sq7uncom {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: transparent;
}
.ldio-0qu31ifis2pl {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0qu31ifis2pl div { box-sizing: content-box; }
/* generated by https://loading.io/ */

/* SKELETON */
.skeleton {
  animation: skeleton-loading 1s linear infinite alternate;
}

@keyframes skeleton-loading {
  0% {
    background-color: hsl(200, 20%, 80%);
  }
  100% {
    background-color: hsl(200, 20%, 95%);
  }
}

.skeleton-text {
  width: 100%;
  height: 0.7rem;
  margin-bottom: 0.5rem;
  border-radius: 0.25rem;
}

.skeleton-text__body {
  width: 75%;
}

.skeleton-footer {
  width: 30%;
}
</style>